### PR TITLE
Make Changes to Several Parts of Core API

### PR DESCRIPTION
**Pull request by seriaati**
Read the commit messages to for a summary of changes made in this PR.
The run script is added back because if there are 2 python files with the same name (in this case `response.py`), Python will fuck up when you only do `from responses import ...`, and specifying `from api.responses import ...` will result in an `ImportError` when trying to launch the API from `app.py`.
Plus, it is more obvious that `responses.py` is a custom module in the project, when using `from api.responses import ...` instead of just `from responses import ...`, which makes me confuse `responses` as a 3rd party library since the line is being formatted to the same block with other 3rd party imports.
This PR also finalizes the convention of creating endpoints in the core API, such as creating custom response models for better docs generation. Please follow the practices used in `user/router.py` when making new endpoints in the future.

### CODE REVIEW

**Comment by jokelbaf** [comment]
There is no way I accept adding run script back. Also the whole current api structure seems quite weird to me. Will take a closer look and update you about this later, leave the PR open for now

**Comment by seriaati** [comment]
I don't add the run script for no reason, I added it back because something is not working without it. If there are other solutions I can adopt it.
For the project structure, I'm mostly following [FastAPI best practices](https://github.com/zhanymkanov/fastapi-best-practices?tab=readme-ov-file#1-project-structure-consistent--predictable) with some modifications to the file name based on my personal preference.

**Comment by jokelbaf** [comment]
> I don't add the run script for no reason, I added it back because something is not working without it. If there are other solutions I can adopt it.

I understand this and, as I said, I will look into the problem when I have time.

> For the project structure, I'm mostly following [FastAPI best practices](https://github.com/zhanymkanov/fastapi-best-practices?tab=readme-ov-file#1-project-structure-consistent--predictable) with some modifications to the file name based on my personal preference.

I noted that. These "best practices" are opinoin-based and I personally don't consider them suitable for this project. The level of modules abstraction there is way too low for us, too many files are mixed together which may prevent some parts of the app from communicating with others.

My point is that the two issues might be related, solving one issue could potentially help us to solve another one.

**Comment by thesadru** [comment]
Why is the run script not in `__main__.py`?

**Comment by seriaati** [comment]
Because the core API is not a package

**Comment by thesadru** [comment]
I don't think that should matter

**Comment by seriaati** [comment]
`__main__.py` is only [specified](https://docs.python.org/3/library/__main__.html) to be used in Python packages.
`__main__.py` is used to allow the package to be executed as a script with `python -m <package_name>`, it doesn't make sense to use such command for the core API.
For projects, a script name like `run.py` is more meaningful and clear to indicate that this should be the entry point to "run" this project.

**Comment by thesadru** [comment]
dunno, I personally make my server code a module and include a `__main__.py`. I wouldn't say it's that weird. 

It's probably gonna be made a module anyways once we're gonna want relative imports

**Pull request merged**
